apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: prod
  labels:
    app: backend
spec:
  ports:
  - port: 9000
    targetPort: 9000
    name: backend
  selector:
    app: backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: vladpugachev/backend:0.4
        ports:
          - containerPort: 9000
        imagePullPolicy: IfNotPresent
        name: backend
      imagePullSecrets:
        - name: regcred
