apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgress-prod-pv-claim
  namespace: prod
spec:
  storageClassName: prod
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi